### ISSUE TITLE
Android Compatibility

### ISSUE THREAD

**Issue by rogersala** [gitgrimbo/android-sliding-menu-demo#2]
Hi,

First of all, thanks for share your code. That's very useful for me on Android 2.2 and 2.3! I just have one problem. Your library it's not working on Android 3.0 (Tablet) and 4.0 (both). It crashes me all the time. The error is: observer is null. And it is produced in line "parent.removeAllViews() (I remembered). 

Do you have any idea, or how to change the code to works in Android 3.0 or above?

I'm waiting for your response,

Roger

**Comment by rogersala** [comment]
Hi,

Sorry for my question. It works! It was my fault. Sorry again. And congratulations for your project!! Great

**Comment by gitgrimbo** [comment]
Glad to hear it's working! I wouldn't have been all that much help tbh, as I've not tried Android 3 and 4. Maybe if/when I get a new phone I can take a look! :)
